# Mock用のAPIのためのAPI定義
openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a user
      description: Creates a new user in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user
                  example: John Doe
                email:
                  type: string
                  description: The email address of the user
                  example: johndoe@example.com
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the newly created user
                    example: 1
                  name:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    example: johndoe@example.com
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                    example: Invalid request body
  /products:
    post:
      summary: Create a product
      description: Creates a new product in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the product
                  example: Acme Widget
                description:
                  type: string
                  description: A description of the product
                  example: This is a great widget!
                price:
                  type: number
                  description: The price of the product
                  example: 19.95
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the newly created product
                    example: 1
                  name:
                    type: string
                    example: Acme Widget
                  description:
                    type: string
                    example: This is a great widget!
                  price:
                    type: number
                    example: 19.95
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                    example: Invalid request body
  /orders:
    post:
      summary: Create an order
      description: Creates a new order in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: The ID of the user who is placing the order
                  example: 1
                productId:
                  type: integer
                  description: The ID of the product being ordered
                  example: 1
                quantity:
                  type: integer
                  description: The quantity of the product being ordered
                  example: 2
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the newly created order
                    example: 1
                  userId:
                    type: integer
                    example: 1
                  productId:
                    type: integer
                    example: 1
                  quantity:
                    type: integer
                    example: 2
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                    example: Invalid request body
